
version: '{build}.0.0-dev'
image: Visual Studio 2019
pull_requests:
  do_not_increment_build_number: true


matrix:
  fast_finish: true


configuration:
  - Debug
  - Release


# Override the 'version' if this is a GH-tag-commit -or- this is a custom branch (i.e not 'master').
init:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq $TRUE -and $env:APPVEYOR_REPO_BRANCH -eq 'master')
      { 
          Write-Host " !! Commit is Tagged and branch is 'master' - forcing build version to tag-value." -ForegroundColor Red; 
          Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME"
      }
      iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))


before_build:
  # Display .NET Core version
  - ps: dotnet --info


build_script:
  - ps: dotnet restore --verbosity quiet
  - ps: dotnet build -c $env:CONFIGURATION -v minimal /p:Version=$env:APPVEYOR_BUILD_VERSION --no-restore


test_script:
  -  ps: dotnet test -c $env:CONFIGURATION -v minimal --no-build


# We only:
#   - Pack for RELEASE only.
after_test:
  - ps: |
      if ($env:CONFIGURATION -eq 'Release')
      {
          dotnet pack -c $env:CONFIGURATION --include-symbols -p:SymbolPackageFormat=snupkg /p:Version=$env:APPVEYOR_BUILD_VERSION --no-build
      }


artifacts:
  - path: '**\*.nupkg'
    name: nuget-packages
    type: NuGetPackage
  - path: '**\*.snupkg'
    name: nuget-symbols
    type: NuGetPackage


deploy:
  - provider: NuGet
    server: https://www.myget.org/F/openrealestate-net/api/v2/package
    api_key:
      secure: AguzfXNvHBkkDebTyWHK7o9OC5YL3eszT6u7PnzGq2G7ozdUypDlGGpcFsTRYHEc
    artifact: nuget-packages # myget does now support symbols BUT appveyor doesn't publish it correctly
    on:
      CONFIGURATION: Release
      APPVEYOR_REPO_TAG: false
  - provider: NuGet
    server: https://www.myget.org/F/openrealestate/api/v2/package
    api_key:
      secure: AguzfXNvHBkkDebTyWHK7o9OC5YL3eszT6u7PnzGq2G7ozdUypDlGGpcFsTRYHEc
    artifact: nuget-packages # myget does now support symbols BUT appveyor doesn't publish it correctly
    on:
      CONFIGURATION: Release
      APPVEYOR_REPO_BRANCH: master
      APPVEYOR_REPO_TAG: true
